ExamWatchers/Controllers/CollegesController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Models;

namespace ExamWatchers.Controllers
{
    [AuthorizeRoles(SecurityRoles.Admin)]
    public class CollegesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Colleges
        public ActionResult Index()
        {
            return View(db.Colleges.ToList());
        }

        // GET: Colleges/ExamPlaces/5
        public ActionResult ExamPlaces(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var college = db.Colleges.Include(c => c.ExamPlaces).FirstOrDefault(c => c.Id == id);
            if (college == null)
                return HttpNotFound();

            ViewBag.CollegeTitle = college.Title;
            ViewBag.CollegeId = college.Id;
            return View(college.ExamPlaces.ToList());
        }

        public ActionResult Exams(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var college = db.Colleges.Include(c => c.ExamPlaces.Select(s => s.Exams.Select(e => e.Watchers))).FirstOrDefault(c => c.Id == id);
            if (college == null)
                return HttpNotFound();

            ViewBag.CollegeTitle = college.Title;
            ViewBag.CollegeId = college.Id;
            return View(college.ExamPlaces.SelectMany(s => s.Exams).ToList());
        }

        // GET: Colleges/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            College college = db.Colleges.Find(id);
            if (college == null)
            {
                return HttpNotFound();
            }
            return View(college);
        }

        // GET: Colleges/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Colleges/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(College college)
        {
            if (ModelState.IsValid)
            {
                db.Colleges.Add(college);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(college);
        }

        // GET: Colleges/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            College college = db.Colleges.Find(id);
            if (college == null)
            {
                return HttpNotFound();
            }
            return View(college);
        }

        // POST: Colleges/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(College college)
        {
            if (ModelState.IsValid)
            {
                db.Entry(college).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(college);
        }

        // GET: Colleges/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            College college = db.Colleges.Find(id);
            if (college == null)
            {
                return HttpNotFound();
            }
            return View(college);
        }

        // POST: Colleges/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            College college = db.Colleges.Find(id);
            db.Colleges.Remove(college);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ExamWatchers/Controllers/ExamsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ExamWatchers.ViewModels;
using Models;
using Stimulsoft.Report;
using Stimulsoft.Report.Dictionary;
using Stimulsoft.Report.Mvc;

namespace ExamWatchers.Controllers
{
    [AuthorizeRoles(SecurityRoles.Admin, SecurityRoles.CollegeAdmin)]
    public class ExamsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Exams
        public ActionResult Index()
        {
            // واکشی آیدی دانشکده هایی که کاربر جاری بهشون دسترسی داره
            // اگه کاربر جاری نقش ادمین رو داشت، پس مجازه که به کل دانشکده ها دسترسی داشته باشه
            IEnumerable<int> accessedCollegeIds;
            if (User.IsInRole(SecurityRoles.Admin))
                accessedCollegeIds = db.Colleges.Select(s => s.Id);
            else
            {
                accessedCollegeIds = db.Users.FirstOrDefault(u => u.PersonnelCode == User.Identity.Name).Accesses.Select(s => s.CollegeId);
            }

            var exams = db.Exams.Include(e => e.Watchers)
                .Include(e => e.ExamPlace)
                .Where(e => accessedCollegeIds.Contains(e.ExamPlace.CollegeId));
            return View(exams.ToList());
        }

        [HttpGet]
        public ActionResult Watchers(string id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var exam = db.Exams.Include(e => e.Watchers).FirstOrDefault(e => e.Code == id);
            if (exam == null)
                return HttpNotFound();

            ViewBag.ExamTitle = exam.Title;
            ViewBag.ExamCode = exam.Code;
            var examsList = exam.Watchers
                .Select(s => new ExamWatcherDetailsViewModel
                {
                    WatcherCode = s.WatcherCode,
                    WatcherName = s.Watcher.User.FirstName + " " + s.Watcher.User.LastName,
                    SubmitDate = s.SubmitDate
                }).ToList();
            return View(examsList);
        }

        // GET: Exams/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exam exam = db.Exams.Find(id);
            if (exam == null)
            {
                return HttpNotFound();
            }
            return View(exam);
        }

        // GET: Exams/Create
        public ActionResult Create()
        {
            //var vm = new CreateExamViewModel
            //{
            //    ExamStartTime = DateTime.Now.AddDays(5).Date
            //};

            IEnumerable<College> colleges;
            if (User.IsInRole(SecurityRoles.Admin))
                colleges = db.Colleges;
            else
            {
                // واکشی آیدی دانشکده هایی که کاربر جاری بهشون دسترسی داره
                var accessedCollegeIds = db.Users.FirstOrDefault(u => u.PersonnelCode == User.Identity.Name).Accesses.Select(s => s.CollegeId);
                colleges = db.Colleges.Where(c => accessedCollegeIds.Contains(c.Id));
            }

            ViewBag.CollegeId = new SelectList(colleges
                .Select(c => new
                {
                    c.Id,
                    c.Title,
                }), "Id", "Title");

            ViewBag.ExamPlaceId = new SelectList(db.ExamPlaces, "Id", "Title");
            return View();
        }

        // POST: Exams/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateExamViewModel vm)
        {
            if (ModelState.IsValid)
            {
                string startTime = vm.ExamStartTime.ToAsciiNumbers();
                string endTime = vm.ExamEndTime.ToAsciiNumbers();
                string endDateTime = startTime.Split(' ')[0] + " " + endTime;

                var exam = new Exam
                {
                    Code = vm.Code,
                    ExamPlaceId = vm.ExamPlaceId,
                    //RemainingCapacity = vm.WatchersCapacity,
                    Title = vm.Title,
                    WatchersCapacity = vm.WatchersCapacity,
                    ExamStartTime = DateTime.Parse(startTime),
                    ExamEndTime = DateTime.Parse(endDateTime)
                };

                db.Exams.Add(exam);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            IEnumerable<College> colleges;
            if (User.IsInRole(SecurityRoles.Admin))
                colleges = db.Colleges;
            else
            {
                // واکشی آیدی دانشکده هایی که کاربر جاری بهشون دسترسی داره
                var accessedCollegeIds = db.Users.FirstOrDefault(u => u.PersonnelCode == User.Identity.Name).Accesses.Select(s => s.CollegeId);
                colleges = db.Colleges.Where(c => accessedCollegeIds.Contains(c.Id));
            }

            ViewBag.CollegeId = new SelectList(colleges
                .Select(c => new
                {
                    c.Id,
                    c.Title,
                }), "Id", "Title", vm.CollegeId);

            ViewBag.ExamPlaceId = new SelectList(db.ExamPlaces, "Id", "Title", vm.ExamPlaceId);
            return View(vm);
        }

        // GET: Exams/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exam exam = db.Exams.Include(e => e.ExamPlace).FirstOrDefault(e => e.Code == id);
            if (exam == null)
            {
                return HttpNotFound();
            }

            var viewModel = new CreateExamViewModel
            {
                Code = exam.Code,
                Title = exam.Title,
                CollegeId = exam.ExamPlace.CollegeId,
                ExamStartTime = exam.ExamStartTime.ToString(),
                ExamEndTime = exam.ExamEndTime.ToString(),
                //ExamStartTime = exam.ExamStartTime,
                //ExamEndTime = exam.ExamEndTime,
                ExamPlaceId = exam.ExamPlaceId,
                WatchersCapacity = exam.WatchersCapacity,
                //RemainingCapacity = exam.RemainingCapacity
            };

            IEnumerable<College> colleges;
            if (User.IsInRole(SecurityRoles.Admin))
                colleges = db.Colleges;
            else
            {
                // واکشی آیدی دانشکده هایی که کاربر جاری بهشون دسترسی داره
                var accessedCollegeIds = db.Users.FirstOrDefault(u => u.PersonnelCode == User.Identity.Name).Accesses.Select(s => s.CollegeId);
                colleges = db.Colleges.Where(c => accessedCollegeIds.Contains(c.Id));
            }

            ViewBag.CollegeId = new SelectList(colleges
                .Select(c => new
                {
                    c.Id,
                    c.Title,
                }), "Id", "Title", exam.ExamPlace.CollegeId);

            ViewBag.ExamPlaceId = new SelectList(db.ExamPlaces, "Id", "Title", exam.ExamPlaceId);
            return View(viewModel);
        }

        // POST: Exams/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CreateExamViewModel vm)
        {
            if (ModelState.IsValid)
            {
                string startTime = vm.ExamStartTime.ToAsciiNumbers();
                string endTime = vm.ExamEndTime.ToAsciiNumbers();
                string endDateTime = startTime.Split(' ')[0] + " " + endTime;

                var exam = new Exam
                {
                    Code = vm.Code,
                    Title = vm.Title,
                    ExamPlaceId = vm.ExamPlaceId,
                    WatchersCapacity = vm.WatchersCapacity,
                    //RemainingCapacity = vm.RemainingCapacity,
                    ExamStartTime = DateTime.Parse(startTime),
                    ExamEndTime = DateTime.Parse(endDateTime)
                };

                db.Entry(exam).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            IEnumerable<College> colleges;
            if (User.IsInRole(SecurityRoles.Admin))
                colleges = db.Colleges;
            else
            {
                // واکشی آیدی دانشکده هایی که کاربر جاری بهشون دسترسی داره
                var accessedCollegeIds = db.Users.FirstOrDefault(u => u.PersonnelCode == User.Identity.Name).Accesses.Select(s => s.CollegeId);
                colleges = db.Colleges.Where(c => accessedCollegeIds.Contains(c.Id));
            }

            ViewBag.CollegeId = new SelectList(colleges
                .Select(c => new
                {
                    c.Id,
                    c.Title,
                }), "Id", "Title", vm.CollegeId);

            ViewBag.ExamPlaceId = new SelectList(db.ExamPlaces, "Id", "Title", vm.ExamPlaceId);
            return View(vm);
        }

        // GET: Exams/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exam exam = db.Exams.Find(id);
            if (exam == null)
            {
                return HttpNotFound();
            }
            return View(exam);
        }

        // POST: Exams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Exam exam = db.Exams.Find(id);
            db.Exams.Remove(exam);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public JsonResult FillPlaces(int collegeId)
        {

ExamWatchers/Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - سیستم مدیریت مراقبین</title>
    @*@Styles.Render("~/Content/css")*@
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("Styles", false)
    <link href="~/Content/bootstrap-flatly.css" rel="stylesheet" />
    <link href="~/Content/AccountStyle.css" rel="stylesheet" />
</head>
<body>
    <div class="my-container">
        <div class="container-form">
            <div class="wrap-account">
                <div class="wrap-account-pic col-lg-6 col-md-6 hidden-sm hidden-xs" style="background-image: url('../../Content/Images/Register.jpg')"></div>
                <div class="account-form col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <span class="account-form-title" style="margin-bottom: 40px">
                        @ViewBag.Title
                    </span>

                    @RenderBody()
                    @*<div class="container body-content">
                            @RenderBody()
                            <hr />
                            <footer>
                                <p class="copyright">&copy; @DateTime.Now.Year - Watchers</p>
                            </footer>
                        </div>*@
                </div>
                @*<script src="/Scripts/jquery-1.10.2.min.js"></script>
                    <script src="/Scripts/jquery.validate.min.js"></script>
                    <script src="/Scripts/jquery.validate.unobtrusive.min.js"></script>*@
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ExamWatchers/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - سیستم مدیریت مراقبین</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("Styles", false)

    @{
        var db = new Models.ApplicationDbContext();
        var user = db.Users.FirstOrDefault(u => u.PersonnelCode == User.Identity.Name);
    }
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("سیستم مدیریت مراقبین", "Login", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @{
                        if (User.IsInRole(Models.SecurityRoles.Admin))
                        {
                            <li>@Html.ActionLink("دانشکده ها", "Index", "Colleges")</li>
                            <li>@Html.ActionLink("حوزه های امتحانی", "Index", "ExamPlaces")</li>
                            <li>@Html.ActionLink("امتحانات", "Index", "Exams")</li>
                            <li>@Html.ActionLink("کاربران", "Index", "Users")</li>
                            <li>@Html.ActionLink("مراقبین", "Index", "Watchers")</li>
                            <li>@Html.ActionLink("حضور مراقبین", "Index", "WatcherExams")</li>
                        }
                        else if (User.IsInRole(Models.SecurityRoles.CollegeAdmin))
                        {
                            <li>@Html.ActionLink("حوزه های امتحانی", "Index", "ExamPlaces")</li>
                            <li>@Html.ActionLink("امتحانات", "Index", "Exams")</li>
                            <li>@Html.ActionLink("مراقبین", "Index", "Watchers")</li>
                            <li>@Html.ActionLink("حضور مراقبین", "Index", "WatcherExams")</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("امتحانات", "Exams", "WatcherExams")</li>
                        }
                    }
                </ul>
                <ul class="nav navbar-nav navbar-left">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="fa fa-user-circle-o" style="font-size:16px; margin-left:5px;vertical-align: middle;"></i> <span>@(user.FirstName + " " + user.LastName)</span> <i class="icon-submenu fa fa-chevron-down"></i></a>
                        <ul class="dropdown-menu">
                            @*<li><a href="~/Manage/"><i class="fa fa-cogs"></i> <span>تنظیمات</span></a></li>*@
                            <li>
                                @using (Html.BeginForm("LogOff", "Home", FormMethod.Post, new { id = "logoutForm" }))
                                {
                                    @Html.AntiForgeryToken()
                                    <a href="javascript:document.getElementById('logoutForm').submit()">
                                        <i class="lnr lnr-exit" style="vertical-align: middle;"></i> <span>خروج</span>
                                    </a>
                                }
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="copyright">&copy; @DateTime.Now.Year - سیستم مدیریت مراقبین</p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/unobtrusive")*@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/datatables")
    @RenderSection("scripts", required: false)
</body>
</html>