ExamWatchers/ViewModels/CollegeViewModel.cs
namespace ExamWatchers.ViewModels
{
    public class CollegeViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public bool IsSelected { get; set; }
    }
}

ExamWatchers/Controllers/CollegesController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Models;

namespace ExamWatchers.Controllers
{
    [AuthorizeRoles(SecurityRoles.Admin)]
    public class CollegesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Colleges
        public ActionResult Index()
        {
            return View(db.Colleges.ToList());
        }

        // GET: Colleges/ExamPlaces/5
        public ActionResult ExamPlaces(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var college = db.Colleges.Include(c => c.ExamPlaces).FirstOrDefault(c => c.Id == id);
            if (college == null)
                return HttpNotFound();

            ViewBag.CollegeTitle = college.Title;
            ViewBag.CollegeId = college.Id;
            return View(college.ExamPlaces.ToList());
        }

        public ActionResult Exams(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var college = db.Colleges.Include(c => c.ExamPlaces.Select(s => s.Exams.Select(e => e.Watchers))).FirstOrDefault(c => c.Id == id);
            if (college == null)
                return HttpNotFound();

            ViewBag.CollegeTitle = college.Title;
            ViewBag.CollegeId = college.Id;
            return View(college.ExamPlaces.SelectMany(s => s.Exams).ToList());
        }

        // GET: Colleges/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            College college = db.Colleges.Find(id);
            if (college == null)
            {
                return HttpNotFound();
            }
            return View(college);
        }

        // GET: Colleges/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Colleges/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(College college)
        {
            if (ModelState.IsValid)
            {
                db.Colleges.Add(college);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(college);
        }

        // GET: Colleges/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            College college = db.Colleges.Find(id);
            if (college == null)
            {
                return HttpNotFound();
            }
            return View(college);
        }

        // POST: Colleges/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(College college)
        {
            if (ModelState.IsValid)
            {
                db.Entry(college).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(college);
        }

        // GET: Colleges/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            College college = db.Colleges.Find(id);
            if (college == null)
            {
                return HttpNotFound();
            }
            return View(college);
        }

        // POST: Colleges/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            College college = db.Colleges.Find(id);
            db.Colleges.Remove(college);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ExamWatchers/Controllers/ExamPlacesController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Models;

namespace ExamWatchers.Controllers
{
    [AuthorizeRoles(SecurityRoles.Admin, SecurityRoles.CollegeAdmin)]
    public class ExamPlacesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ExamPlaces
        public ActionResult Index()
        {
            // واکشی آیدی دانشکده هایی که کاربر جاری بهشون دسترسی داره
            // اگه کاربر جاری نقش ادمین رو داشت، پس مجازه که به کل دانشکده ها دسترسی داشته باشه
            IEnumerable<int> accessedCollegeIds;
            if (User.IsInRole(SecurityRoles.Admin))
                accessedCollegeIds = db.Colleges.Select(s => s.Id);
            else
            {
                accessedCollegeIds = db.Users.FirstOrDefault(u => u.PersonnelCode == User.Identity.Name).Accesses.Select(s => s.CollegeId);
            }

            var examPlaces = db.ExamPlaces.Include(e => e.College).Where(e => accessedCollegeIds.Contains(e.CollegeId));
            return View(examPlaces.ToList());
        }

        public ActionResult Exams(int? placeId)
        {
            if (placeId == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var place = db.ExamPlaces.Include(p => p.Exams.Select(e => e.Watchers)).FirstOrDefault(p => p.Id == placeId);
            if (place == null)
                return HttpNotFound();

            ViewBag.PlaceId = place.Id;
            ViewBag.PlaceTitle = place.Title;
            return View(place.Exams.ToList());
        }

        // GET: ExamPlaces/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExamPlace examPlace = db.ExamPlaces.Find(id);
            if (examPlace == null)
            {
                return HttpNotFound();
            }
            return View(examPlace);
        }

        // GET: ExamPlaces/Create
        public ActionResult Create()
        {
            IEnumerable<College> colleges;
            if (User.IsInRole(SecurityRoles.Admin))
                colleges = db.Colleges;
            else
            {
                // واکشی آیدی دانشکده هایی که کاربر جاری بهشون دسترسی داره
                var accessedCollegeIds = db.Users.FirstOrDefault(u => u.PersonnelCode == User.Identity.Name).Accesses.Select(s => s.CollegeId);
                colleges = db.Colleges.Where(c => accessedCollegeIds.Contains(c.Id));
            }

            ViewBag.CollegeIds = new SelectList(colleges
                .Select(c => new
                {
                    c.Id,
                    c.Title,
                }), "Id", "Title");

            return View();
        }

        // POST: ExamPlaces/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ExamPlace examPlace)
        {
            if (ModelState.IsValid)
            {
                db.ExamPlaces.Add(examPlace);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            // واکشی دانشکده هایی که کاربر جاری بهشون دسترسی داره
            // اگر کاربر جاری نقش مدیر سیستم رو داشت پس مجازه که به کل دانشکده ها دسترسی داشته باشه
            IEnumerable<College> colleges;
            if (User.IsInRole(SecurityRoles.Admin))
                colleges = db.Colleges;
            else
            {
                // واکشی آیدی دانشکده هایی که کاربر جاری بهشون دسترسی داره
                var accessedCollegeIds = db.Users.FirstOrDefault(u => u.PersonnelCode == User.Identity.Name).Accesses.Select(s => s.CollegeId);
                colleges = db.Colleges.Where(c => accessedCollegeIds.Contains(c.Id));
            }

            ViewBag.CollegeIds = new SelectList(colleges
                .Select(c => new
                {
                    c.Id,
                    c.Title,
                }), "Id", "Title", examPlace.CollegeId);

            return View(examPlace);
        }

        // GET: ExamPlaces/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExamPlace examPlace = db.ExamPlaces.Find(id);
            if (examPlace == null)
            {
                return HttpNotFound();
            }

            // واکشی دانشکده هایی که کاربر جاری بهشون دسترسی داره
            // اگر کاربر جاری نقش مدیر سیستم رو داشت پس مجازه که به کل دانشکده ها دسترسی داشته باشه
            IEnumerable<College> colleges;
            if (User.IsInRole(SecurityRoles.Admin))
                colleges = db.Colleges;
            else
            {
                // واکشی آیدی دانشکده هایی که کاربر جاری بهشون دسترسی داره
                var accessedCollegeIds = db.Users.FirstOrDefault(u => u.PersonnelCode == User.Identity.Name).Accesses.Select(s => s.CollegeId);
                colleges = db.Colleges.Where(c => accessedCollegeIds.Contains(c.Id));
            }

            ViewBag.CollegeIds = new SelectList(colleges
                .Select(c => new
                {
                    c.Id,
                    c.Title,
                }), "Id", "Title", examPlace.CollegeId);

            return View(examPlace);
        }

        // POST: ExamPlaces/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ExamPlace examPlace)
        {
            if (ModelState.IsValid)
            {
                db.Entry(examPlace).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            // واکشی دانشکده هایی که کاربر جاری بهشون دسترسی داره
            // اگر کاربر جاری نقش مدیر سیستم رو داشت پس مجازه که به کل دانشکده ها دسترسی داشته باشه
            IEnumerable<College> colleges;
            if (User.IsInRole(SecurityRoles.Admin))
                colleges = db.Colleges;
            else
            {
                // واکشی آیدی دانشکده هایی که کاربر جاری بهشون دسترسی داره
                var accessedCollegeIds = db.Users.FirstOrDefault(u => u.PersonnelCode == User.Identity.Name).Accesses.Select(s => s.CollegeId);
                colleges = db.Colleges.Where(c => accessedCollegeIds.Contains(c.Id));
            }

            ViewBag.CollegeIds = new SelectList(colleges
                .Select(c => new
                {
                    c.Id,
                    c.Title,
                }), "Id", "Title", examPlace.CollegeId);

            return View(examPlace);
        }

        // GET: ExamPlaces/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExamPlace examPlace = db.ExamPlaces.Find(id);
            if (examPlace == null)
            {
                return HttpNotFound();
            }
            return View(examPlace);
        }

        // POST: ExamPlaces/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ExamPlace examPlace = db.ExamPlaces.Find(id);
            db.ExamPlaces.Remove(examPlace);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ExamWatchers/Views/Colleges/Create.cshtml
@model Models.College

@{
    ViewBag.Title = "تعریف دانشکده جدید";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>دانشکده جدید</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ثبت" class="btn btn-default col-md-12" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("بازگشت به لیست", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ExamWatchers/Views/Colleges/Delete.cshtml
@model Models.College

@{
    ViewBag.Title = "حذف دانشکده";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>حذف دانشکده</h2>

<h3>آیا از حذف این دانشکده اطمینان دارید؟</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd class="numeric">
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="حذف" class="btn btn-default" /> |
            @Html.ActionLink("بازگشت به لیست", "Index")
        </div>
    }
</div>

ExamWatchers/Views/Colleges/Details.cshtml
@model Models.College

@{
    ViewBag.Title = "جزئیات دانشکده";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>جزئیات دانشکده</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd class="numeric">
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("ویرایش", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("بازگشت به لیست", "Index")
</p>

ExamWatchers/Views/Colleges/Edit.cshtml
@model Models.College

@{
    ViewBag.Title = "ویرایش دانشکده";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ویرایش دانشکده</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ثبت تغییرات" class="btn btn-default col-md-12" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("بازگشت به لیست", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ExamWatchers/Views/Colleges/ExamPlaces.cshtml
@model IEnumerable<Models.ExamPlace>

@{
    ViewBag.Title = "حوزه های امتحانی";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>حوزه های امتحانی @ViewBag.CollegeTitle</h2>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
<table id="table" class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            @*<th>
                    @Html.DisplayNameFor(model => model.College.Title)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModifiedDate)
            </th>
            @*<th></th>*@
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @*<td>
                        @Html.DisplayFor(modelItem => item.College.Title)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td class="numeric">
                    @Html.DisplayFor(modelItem => item.ModifiedDate)
                </td>
                @*<td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>*@
            </tr>
        }
    </tbody>
</table>

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $("#table").DataTable({
                language: {
                    search: "جستجو:",
                    emptyTable: "<span style='color:red;'>داده ای برای نمایش وجود ندارد!</span>",
                    processing: "درحال واکشی اطلاعات...",
                    loadingRecords: "درحال واکشی اطلاعات...",
                    zeroRecords: "موردی یافت نشد!",
                    lengthMenu: "نمایش &nbsp;_MENU_&nbsp; رکورد",
                    info: "نمایش رکوردهای _START_ الی _END_ از مجموع _TOTAL_ رکورد",
                    infoEmpty: "نمایش رکوردهای 0 الی 0 از مجموع 0 رکورد",
                    infoFiltered: "",
                    paginate: {
                        next: "بعدی",
                        previous: "قبلی"
                    }
                }
            });
        });
    </script>
}

ExamWatchers/Views/Colleges/Exams.cshtml
@model IEnumerable<Models.Exam>

@{
    ViewBag.Title = "Exams";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>امتحانات @ViewBag.CollegeTitle</h2>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
<table id="table" class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                حوزه
            </th>
            <th>
                تاریخ امتحان
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WatchersCapacity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RemainingCapacity)
            </th>
            @*<th></th>*@
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ExamPlace.Title)
                </td>
                <td class="numeric">
                    @(item.ExamStartTime.ToString("yyyy/MM/dd HH:mm") + " - " + item.ExamEndTime.ToString("HH:mm"))
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WatchersCapacity)
                </td>
                <td>
                    @if (item.RemainingCapacity == 0)
                    {
                        <span class="text-danger">تکمیل شده</span>
                    }
                    else
                    {
                        @Html.DisplayFor(modelItem => item.RemainingCapacity)
                    }
                </td>
                @*<td>
                        @Html.ActionLink("Edit", "Edit", new { id=item.Code }) |
                        @Html.ActionLink("Details", "Details", new { id=item.Code }) |
                        @Html.ActionLink("Delete", "Delete", new { id=item.Code })
                    </td>*@
            </tr>
        }
    </tbody>
</table>

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $("#table").DataTable({
                language: {
                    search: "جستجو:",
                    emptyTable: "<span style='color:red;'>داده ای برای نمایش وجود ندارد!</span>",
                    processing: "درحال واکشی اطلاعات...",
                    loadingRecords: "درحال واکشی اطلاعات...",
                    zeroRecords: "موردی یافت نشد!",
                    lengthMenu: "نمایش &nbsp;_MENU_&nbsp; رکورد",
                    info: "نمایش رکوردهای _START_ الی _END_ از مجموع _TOTAL_ رکورد",
                    infoEmpty: "نمایش رکوردهای 0 الی 0 از مجموع 0 رکورد",
                    infoFiltered: "",
                    paginate: {
                        next: "بعدی",
                        previous: "قبلی"
                    }
                }
            });
        });
    </script>
}

ExamWatchers/Views/Colleges/Index.cshtml
@model IEnumerable<Models.College>

@{
    ViewBag.Title = "لیست دانشکده ها";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>دانشکده ها</h2>

<p>
    @Html.ActionLink("دانشکده جدید", "Create", null, new { @class = "btn btn-primary" })
</p>
<table id="table" class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModifiedDate)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td class="numeric">
                    @Html.DisplayFor(modelItem => item.ModifiedDate)
                </td>
                <td>
                    @Html.ActionLink("ویرایش", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("مشاهده", "Details", new { id = item.Id }) |
                    @Html.ActionLink("حذف", "Delete", new { id = item.Id }) |
                    @Html.ActionLink("حوزه های امتحانی", "ExamPlaces", new { id = item.Id }) |
                    @Html.ActionLink("امتحانات", "Exams", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $("#table").DataTable({
                language: {
                    search: "جستجو:",
                    emptyTable: "<span style='color:red;'>داده ای برای نمایش وجود ندارد!</span>",
                    processing: "درحال واکشی اطلاعات...",
                    loadingRecords: "درحال واکشی اطلاعات...",
                    zeroRecords: "موردی یافت نشد!",
                    lengthMenu: "نمایش &nbsp;_MENU_&nbsp; رکورد",
                    info: "نمایش رکوردهای _START_ الی _END_ از مجموع _TOTAL_ رکورد",
                    infoEmpty: "نمایش رکوردهای 0 الی 0 از مجموع 0 رکورد",
                    infoFiltered: "",
                    paginate: {
                        next: "بعدی",
                        previous: "قبلی"
                    }
                }
            });
        });
    </script>
}